######################################################################
# Automatically generated by qmake (2.01a) ? 10 23 18:49:25 2014
######################################################################

TARGET = iricGccGridgenerator
TEMPLATE = lib
INCLUDEPATH += ../..

DEFINES += GCC_GRIDGENERATOR_LIBRARY

include( ../../../paths.pri )

QT += widgets xml

######################
# Internal libraries #
######################

# iricMisc

unix {
	LIBS += -L"../../misc"
}
LIBS += -liricMisc

# iricGuibase

unix {
	LIBS += -L"../../guibase"
}
LIBS += -liricGuibase

# iricGuicore

unix {
	LIBS += -L"../../guicore"
}
LIBS += -liricGuicore

######################
# External libraries #
######################

# VTK

LIBS += \
	-lvtkCommonComputationalGeometry-6.1 \
	-lvtkCommonCore-6.1 \
	-lvtkCommonDataModel-6.1 \
	-lvtkRenderingCore-6.1 \
	-lvtkRenderingLabel-6.1

win32 {
	DESTDIR = $(SolutionDir)/libdlls/$(Configuration)
	LIBS += -L$(SolutionDir)/libdlls/$(Configuration)
}

# Input
HEADERS += gcc_gridgenerator_global.h \
           gridcreatingconditioncreatorgridgenerator.h \
           gridcreatingconditiongridgenerator.h \
           gridcreatingconditiongridgeneratorsettingdialog.h
FORMS += gridcreatingconditiongridgeneratorsettingdialog.ui
SOURCES += gridcreatingconditioncreatorgridgenerator.cpp \
           gridcreatingconditiongridgenerator.cpp \
           gridcreatingconditiongridgeneratorsettingdialog.cpp
TRANSLATIONS += languages/iricGccGridgenerator_es_ES.ts \
                languages/iricGccGridgenerator_fr_FR.ts \
                languages/iricGccGridgenerator_id_ID.ts \
                languages/iricGccGridgenerator_ja_JP.ts \
                languages/iricGccGridgenerator_ko_KR.ts \
                languages/iricGccGridgenerator_ru_RU.ts \
                languages/iricGccGridgenerator_th_TH.ts \
                languages/iricGccGridgenerator_vi_VN.ts \
                languages/iricGccGridgenerator_zh_CN.ts
